Logging of dealid and proposalID during deals, and reporting in finalized task
filecoin-project/dealbot pull request #274
Opened 2021-07-05 17:02 UTC by willscott

2021-07-05 20:40 UTC, willscott commented on tasks/retrieval_deal.go
> +					allRetrievals, err := de.node.ClientListRetrievals(ctx)
are there other things to match on here in pulling out the deal from the retrieval? cc @hannahhoward

2021-07-06 02:26 UTC, willscott commented
fix #271

2021-07-06 23:56 UTC, hannahhoward requested changes
Most of this code is not actually going to work. I'll reach out 1-on-1 to see if we can get the best approach here.

2021-07-06 23:56 UTC, hannahhoward commented on tasks/retrieval_deal.go
> +						for _, maybeOurDeal := range allDeals {
This isn't going to work -- these are not the same DealID. The DealID on storage side is an onchain incrementing integer for all deals in the network. The DealID for retrieval is different -- it's just an off chain incrementing integer per client that has nothing to do with the storage deal id.

2021-07-06 23:56 UTC, hannahhoward commented on tasks/retrieval_deal.go
> +							if maybeOurRetrieval.PayloadCID.Equals(expectedPayload) {
Miner ID Would be another thing we can check -- that's what we use above.

2021-07-06 23:56 UTC, hannahhoward commented on tasks/retrieval_deal.go
> +						for _, maybeOurDeal := range allDeals {
There's not a really great correlation here -- but we could use payload CID + miner ID.... except that can definitely be duplicated. Our best piece of information is what we have locally when we create the retrieval from the storage deal -- when we create the retrieval deal after a storage, we should log the proposal CID.

2021-07-06 23:56 UTC, hannahhoward commented on tasks/storage_deal.go
> +				newState := storagemarket.DealStates[info.State]
This also it not going to work. We don't get the DealID till the deal is on chain unfortunately, so we have to wait till at least the publish point to get the deal ID

2021-07-07 00:46 UTC, hannahhoward approved these changes

2021-07-07 03:09 UTC, merged